language: scala
scala:
  - 2.13.4
  - 2.12.12
jdk:
  - openjdk8

script: |
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: |
  sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

